name: cd

on:
  push:
    branches: [main]

jobs:
  job_id:
    name: Gcloud Authentication
    runs-on: ubuntu-latest

    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: job_id

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Cloud Run
        run: gcloud builds submit --project=notely-467622 --tag us-central1-docker.pkg.dev/notely-467622/notely-ar-repo/notely:latest .
